export const anaNicknames = [
	'Ana Luiza',
	'Ana',
	'Luiza',
	'Amor',
	'Vida',
	'Meu bem',
	'Anoca',
	'Anildinha',
	'Aninha',
	'Aninhazinhainha',
	'Aanaa aa aa',
	'Luizinha',
	'Luizazinha',
	'Lulu',
	'Lôlô',
	'Anilda Luiza',
	'Ana Luizilda',
	'Ana Lôlô',
	'Ana Luquinhas',
	'Aninha Luiza',
	'Aninha Louizinha',
	'Ana Juquinha',
	'Ana Zequinha',
	'Ana Pimposa',
	'Ana Banana',
	'Ana Minha Vida',
	'Ana Cabecinha de Pastel',
	'Ana Cabecinha de Paçoca',
	'Ana Vida Minha',
	'Hehhehe meu amoreco',
	'Minha GATOSA',
	'ANA DELICIA',
	'MINHA DIVA',
	'Minha flor do deserto',
	'Xulezinha',
	'Cabecinha de pão hhfehhheh',
];
